<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Audit Log Compliance Report</title>
  <style>
    @page { margin: 1.2cm 1.2cm 1.6cm 1.2cm; }
    body { font-family: DejaVu Sans, Arial, sans-serif; color: #1f2937; font-size: 9.5px; line-height: 1.4; margin: 0; }

    .header { border-bottom: 2px solid #1f3864; padding-bottom: 10px; margin-bottom: 14px; }
    .header h1 { font-size: 16px; color: #1f3864; margin: 0 0 4px; }
    .header .sub { font-size: 10px; color: #4b5563; }

    .meta { background: #f3f4f6; padding: 8px 12px; border-radius: 4px; margin-bottom: 12px; font-size: 9px; }
    .meta-row { display: block; margin: 2px 0; }
    .meta-label { font-weight: bold; color: #4b5563; display: inline-block; min-width: 110px; }

    table { width: 100%; border-collapse: collapse; }
    th { background: #1f3864; color: #fff; padding: 6px 5px; text-align: left; font-size: 9px; text-transform: uppercase; letter-spacing: 0.03em; font-weight: bold; }
    td { padding: 5px; border-bottom: 1px solid #e5e7eb; font-size: 8.5px; vertical-align: top; }
    tr:nth-child(even) td { background: #fafafa; }

    .actor { font-weight: bold; color: #0f172a; }
    .action-type { font-family: monospace; font-size: 8px; color: #1f3864; }
    .ip { font-family: monospace; font-size: 8px; color: #6b7280; }
    .timestamp { font-family: monospace; font-size: 8px; color: #6b7280; }
    .payload { font-family: monospace; font-size: 7.5px; color: #4b5563; max-width: 320px; word-break: break-all; }

    .footer-note { margin-top: 14px; padding-top: 10px; border-top: 1px solid #e5e7eb; font-size: 8.5px; color: #6b7280; font-style: italic; }
    .truncated { background: #fef3c7; padding: 6px 10px; border-radius: 3px; color: #92400e; font-weight: bold; font-size: 9px; margin: 8px 0; }
    .empty { text-align: center; padding: 30px; color: #9ca3af; font-style: italic; }

    .badge-critical  { background: #fef2f2; color: #991b1b; padding: 1px 5px; border-radius: 3px; font-weight: bold; font-size: 8px; }
    .badge-security  { background: #fef3c7; color: #92400e; padding: 1px 5px; border-radius: 3px; font-weight: bold; font-size: 8px; }
    .badge-normal    { background: #f0f9ff; color: #1e40af; padding: 1px 5px; border-radius: 3px; font-size: 8px; }
  </style>
</head>
<body>

<div class="header">
  <h1>EncryptEd — Audit Log Compliance Report</h1>
  <div class="sub">
    Generated for compliance with Republic Act No. 10173 (Data Privacy Act of 2012)
    and institutional security audit requirements.
  </div>
</div>

<div class="meta">
  <span class="meta-row"><span class="meta-label">Date Range:</span> {{ $dateFrom }} to {{ $dateTo }}</span>
  <span class="meta-row"><span class="meta-label">Generated At:</span> {{ $generatedAt->format('F j, Y \a\t h:i:s A') }}</span>
  <span class="meta-row"><span class="meta-label">Generated By:</span> {{ $generatedBy?->full_name ?? $generatedBy?->username ?? 'System' }} (User ID: {{ $generatedBy?->id ?? 'n/a' }})</span>
  <span class="meta-row"><span class="meta-label">Rows in Report:</span> {{ number_format($totalReturned) }} of {{ number_format($totalMatched) }} total matching</span>
</div>

@if($truncated)
<div class="truncated">
  ⚠ Note: Result set exceeded 5,000 rows and was capped. Narrow the filter or run a smaller date range to capture the remaining entries.
</div>
@endif

@if($logs->isEmpty())
<div class="empty">No audit log entries match the selected criteria.</div>
@else
<table>
  <thead>
    <tr>
      <th style="width: 13%;">Timestamp</th>
      <th style="width: 17%;">Actor</th>
      <th style="width: 18%;">Action</th>
      <th style="width: 10%;">Source IP</th>
      <th style="width: 42%;">Payload</th>
    </tr>
  </thead>
  <tbody>
    @foreach($logs as $log)
    @php
      $isSecurity = in_array($log->action_type, [
        'LOGIN_FAILED','ACCOUNT_LOCKED','PRIVILEGE_VIOLATION','INJECTION_BLOCKED','RATE_LIMIT_EXCEEDED'
      ]);
      $isCritical = in_array($log->action_type, [
        'GRADE_LOCKED','GRADE_FINALIZED','DEACTIVATE_USER','REPORT_CARD_GENERATED'
      ]);
      $badgeClass = $isCritical ? 'badge-critical' : ($isSecurity ? 'badge-security' : 'badge-normal');
    @endphp
    <tr>
      <td class="timestamp">{{ $log->created_at->format('Y-m-d H:i:s') }}</td>
      <td><span class="actor">{{ $log->actor_name ?? 'System' }}</span>@if($log->user_id) <span style="color:#9ca3af;">#{{ $log->user_id }}</span>@endif</td>
      <td><span class="{{ $badgeClass }}">{{ $log->action_type }}</span></td>
      <td class="ip">{{ $log->source_ip ?? '—' }}</td>
      <td class="payload">{{ \Illuminate\Support\Str::limit($log->data_payload, 280) }}</td>
    </tr>
    @endforeach
  </tbody>
</table>
@endif

<div class="footer-note">
  This report is system-generated from the tamper-evident audit log of EncryptEd.
  Each row in the underlying database is chained via SHA-256 — any modification to a historical row breaks the chain.
  Use <code>php artisan audit:verify</code> at any time to revalidate chain integrity.
</div>

</body>
</html>
