<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EncryptEd Audit Report</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            color: #1a202c;
            line-height: 1.6;
        }

        .page-break {
            page-break-after: always;
        }

        .header {
            border-bottom: 3px solid #2d3748;
            padding: 20px 0;
            margin-bottom: 30px;
            text-align: center;
        }

        .header h1 {
            font-size: 24px;
            margin-bottom: 5px;
            color: #1a202c;
        }

        .header p {
            font-size: 12px;
            color: #718096;
        }

        .institution {
            font-size: 11px;
            color: #4a5568;
            margin-top: 10px;
            font-weight: bold;
        }

        .metadata {
            background-color: #f7fafc;
            border: 1px solid #e2e8f0;
            padding: 15px;
            margin-bottom: 30px;
            border-radius: 4px;
            font-size: 12px;
        }

        .metadata-row {
            display: flex;
            justify-content: space-between;
            margin-bottom: 8px;
        }

        .metadata-label {
            font-weight: bold;
            color: #2d3748;
        }

        .metadata-value {
            color: #4a5568;
        }

        .compliance-badge {
            background-color: #c6f6d5;
            color: #22543d;
            padding: 8px 12px;
            border-radius: 4px;
            font-size: 11px;
            font-weight: bold;
            display: inline-block;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        thead {
            background-color: #2d3748;
            color: white;
        }

        th {
            padding: 12px;
            text-align: left;
            font-weight: bold;
            font-size: 11px;
            border: 1px solid #2d3748;
        }

        td {
            padding: 10px 12px;
            border-bottom: 1px solid #e2e8f0;
            font-size: 10px;
        }

        tbody tr:nth-child(even) {
            background-color: #f9fafb;
        }

        tbody tr:hover {
            background-color: #eff2f5;
        }

        .action-badge {
            display: inline-block;
            padding: 3px 8px;
            border-radius: 3px;
            font-size: 9px;
            font-weight: bold;
            white-space: nowrap;
        }

        .action-login { background-color: #dbeafe; color: #1e40af; }
        .action-create { background-color: #dcfce7; color: #166534; }
        .action-update { background-color: #fef3c7; color: #92400e; }
        .action-delete { background-color: #fee2e2; color: #991b1b; }
        .action-lock { background-color: #fecaca; color: #7f1d1d; }
        .action-violation { background-color: #fca5a5; color: #7c2d12; }

        .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #e2e8f0;
            text-align: center;
            font-size: 10px;
            color: #718096;
        }

        .empty-notice {
            text-align: center;
            padding: 40px;
            color: #718096;
            font-size: 12px;
        }

        .report-summary {
            background-color: #edf2f7;
            padding: 15px;
            border-radius: 4px;
            margin-bottom: 20px;
            font-size: 11px;
        }

        .summary-item {
            display: inline-block;
            margin-right: 30px;
        }

        .summary-label {
            font-weight: bold;
            color: #2d3748;
        }
    </style>
</head>
<body>
    {{-- Header --}}
    <div class="header">
        <h1>EncryptEd Audit Report</h1>
        <p>System Event & Security Audit Trail</p>
        <div class="institution">{{ $institution ?? 'Phil. Academy of Sakya' }}</div>
    </div>

    {{-- Compliance Badge --}}
    <div style="text-align: center; margin-bottom: 20px;">
        <span class="compliance-badge">RA 10173 COMPLIANT</span>
    </div>

    {{-- Metadata --}}
    <div class="metadata">
        <div class="metadata-row">
            <span class="metadata-label">Report Type:</span>
            <span class="metadata-value">{{ ucfirst($type ?? 'full') }} Audit Trail</span>
        </div>
        <div class="metadata-row">
            <span class="metadata-label">Generated By:</span>
            <span class="metadata-value">{{ $generatedBy ?? 'System Administrator' }}</span>
        </div>
        <div class="metadata-row">
            <span class="metadata-label">Generated At:</span>
            <span class="metadata-value">{{ $generatedAt ?? now()->format('m/d/Y H:i:s') }}</span>
        </div>
        @if($dateFrom || $dateTo)
        <div class="metadata-row">
            <span class="metadata-label">Date Range:</span>
            <span class="metadata-value">
                {{ $dateFrom ? date('m/d/Y', strtotime($dateFrom)) : 'Start' }} 
                to 
                {{ $dateTo ? date('m/d/Y', strtotime($dateTo)) : 'End' }}
            </span>
        </div>
        @endif
        <div class="metadata-row">
            <span class="metadata-label">Total Records:</span>
            <span class="metadata-value">{{ $logs->count() }} events</span>
        </div>
    </div>

    {{-- Report Summary --}}
    @if($logs->count() > 0)
    <div class="report-summary">
        <div class="summary-item">
            <span class="summary-label">Failed Logins:</span> 
            {{ $logs->where('action_type', 'LOGIN_FAILED')->count() }}
        </div>
        <div class="summary-item">
            <span class="summary-label">Locked Accounts:</span> 
            {{ $logs->whereIn('action_type', ['ACCOUNT_LOCKED'])->count() }}
        </div>
        <div class="summary-item">
            <span class="summary-label">Violations:</span> 
            {{ $logs->where('action_type', 'LIKE', '%VIOLATION%')->count() }}
        </div>
    </div>
    @endif

    {{-- Table --}}
    @if($logs->count() > 0)
        <table>
            <thead>
                <tr>
                    <th style="width: 15%;">Actor</th>
                    <th style="width: 15%;">Action</th>
                    <th style="width: 25%;">Details</th>
                    <th style="width: 20%;">IP Address</th>
                    <th style="width: 15%;">Timestamp</th>
                    <th style="width: 10%;">User ID</th>
                </tr>
            </thead>
            <tbody>
                @foreach($logs as $log)
                <tr>
                    <td>{{ $log->actor_name ?? 'System' }}</td>
                    <td>
                        @php
                            $actionClass = match(true) {
                                str_starts_with($log->action_type, 'LOGIN')  => 'login',
                                str_starts_with($log->action_type, 'CREATE') => 'create',
                                str_starts_with($log->action_type, 'UPDATE') => 'update',
                                str_starts_with($log->action_type, 'DELETE') => 'delete',
                                str_starts_with($log->action_type, 'LOCK')   => 'lock',
                                str_contains($log->action_type, 'VIOLATION') => 'violation',
                                default => 'login',
                            };
                        @endphp
                        <span class="action-badge action-{{ $actionClass }}">{{ $log->action_type }}</span>
                    </td>
                    <td>{{ \Illuminate\Support\Str::limit($log->data_payload ?? 'N/A', 50) }}</td>
                    <td style="font-family: monospace;">{{ $log->source_ip ?? '-' }}</td>
                    <td style="font-family: monospace;">{{ $log->created_at->format('m/d/Y H:i:s') }}</td>
                    <td>{{ $log->user_id ?? '-' }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <div class="empty-notice">
            <p>No records found for the selected criteria.</p>
        </div>
    @endif

    {{-- Footer --}}
    <div class="footer">
        <p>This document is confidential and contains sensitive audit information.</p>
        <p>RA 10173 - Data Privacy Act of 2012 Compliant | Non-Repudiation Enforced</p>
        <p>Generated by EncryptEd System | {{ now()->format('Y-m-d H:i:s') }}</p>
    </div>
</body>
</html>
